version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: nurse-exam-db
    environment:
      MYSQL_ROOT_PASSWORD: Password!given
      MYSQL_DATABASE: nurse_exam_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nurse-exam-api
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=Password!given
      - DB_DATABASE=nurse_exam_db
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      db:
        condition: service_healthy
    command: npm run start:dev

volumes:
  mysql_data:
  
# version: '3.8'

# services:
#   api:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     network_mode: "host"  # This allows the container to access host network
#     environment:
#       - NODE_ENV=development
#       - DB_HOST=127.0.0.1
#       - DB_PORT=3306
#       - DB_USERNAME=root
#       - DB_PASSWORD=Password!given
#       - DB_DATABASE=nurse_exam_db
#     volumes:
#       - .:/app
#       - /app/node_modules
#     command: npm run start:dev


